const P=[
["DAY 1 — UPPER","Upper chest + upper back + side delts",[["Incline DB/BB Press","3 × 6–10","2–3","Upper chest"],["Low-Incline Machine Press","2 × 8–12","2","Upper chest"],["Chest-Supported Row","3 × 6–10","2","Upper back"],["Neutral-Grip Pulldown","3 × 8–12","2","Back"],["Cable Lateral Raise","3 × 12–20","1–2","Side delts #1"],["Rear-Delt Fly","2 × 12–20","1–2","Rear delts"],["EZ-Bar Curl","2 × 8–12","1–2","Biceps"],["Cable Triceps Extension","2 × 10–15","1–2","Triceps"]]],
["DAY 2 — LOWER","Quads + hamstrings + calves",[["Hack Squat / High-Bar Squat","3 × 6–10","2–3","Quads"],["Leg Press","3 × 10–15","2","Quads"],["Seated Leg Curl","3 × 8–12","1–2","Hamstrings"],["Romanian Deadlift","2 × 6–10","2–3","Be conservative initially"],["Standing Calf Raise","4 × 8–12","1–2","Calves #1"],["Seated Calf Raise","2 × 12–20","1–2","Calves"],["Cable Crunch / Ab Wheel","3 × 8–15","1–2","Optional"]]],
["DAY 3 — REST","Recovery",[]],
["DAY 4 — SHOULDERS + ARMS","Shoulder + arm specialization + calves",[["Seated DB/Machine Shoulder Press","3 × 6–10","2","Shoulders"],["Cable Lateral Raise","4 × 10–20","1–2","Side delts #2"],["Machine Lateral Raise","2 × 12–20","1–2","Side delts"],["Reverse Pec Deck","3 × 12–20","1–2","Rear delts"],["Incline DB Curl","3 × 8–12","1–2","Biceps"],["Preacher Curl","3 × 10–15","1–2","Biceps"],["Overhead Cable Extension","3 × 8–12","1–2","Triceps"],["Cable Pushdown","3 × 10–15","1–2","Triceps"],["Standing Calf Raise","3 × 8–12","1–2","Calves #2"],["Seated Calf Raise","2 × 12–20","1–2","Calves"]]],
["DAY 5 — LEGS","Legs + calves",[["Squat / Hack Squat","3 × 6–10","2–3","Quads"],["Leg Extension","3 × 10–15","1–2","Quads"],["Seated Leg Curl","3 × 8–12","1–2","Hamstrings"],["Hip Thrust / Back Extension","2 × 8–12","2","Glutes"],["Leg Press Calf Raise","3 × 10–15","1–2","Calves #3"],["Seated Calf Raise","2 × 12–20","1–2","Calves"],["Abs","3 × 8–15","1–2","Optional"]]],
["DAY 6 — CHEST + BACK","Upper chest + upper back + side delts",[["Incline Barbell Press","3 × 5–8","2","Upper chest"],["Incline Cable Fly","2 × 10–15","1–2","Upper chest"],["Chest-Supported Row","3 × 8–12","2","Upper back"],["Wide/Medium-Grip Pulldown","3 × 8–12","2","Back"],["Cable Row / High Row","2 × 10–15","1–2","Upper back"],["Cable Lateral Raise","3 × 12–20","1–2","Side delts #3"],["Cable Curl","2 × 10–15","1–2","Biceps"],["Overhead Triceps Extension","2 × 10–15","1–2","Triceps"]]],
["DAY 7 — REST","Recovery",[]]];
const K='gymTrackerV43';
let S=JSON.parse(localStorage.getItem(K)||'null')||JSON.parse(localStorage.getItem('gymTrackerV3')||localStorage.getItem('gymTrackerV2')||localStorage.getItem('gymTrackerV1')||'null')||{day:0,workouts:[],metrics:[],active:null};
S.workouts=S.workouts||[];S.metrics=S.metrics||[];S.active=S.active||null;S.day=S.day??0;
const save=()=>localStorage.setItem(K,JSON.stringify(S));
const today=()=>new Date().toISOString().slice(0,10);
const esc=x=>String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[m]));
const parseRange=s=>{let m=s.match(/(\d+)\s*×\s*(\d+)\s*[–-]\s*(\d+)/);return m?{sets:+m[1],min:+m[2],max:+m[3]}:{sets:parseInt(s)||1,min:1,max:99}};
const toast=x=>{let t=document.querySelector('#toast');t.textContent=x;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1700)};
function view(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(v).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===v));render(v);scrollTo({top:0,behavior:'smooth'})}
function render(v){({workout,program,progress,history,settings}[v])()}
function lastForExercise(name){for(let i=S.workouts.length-1;i>=0;i--){let e=S.workouts[i].entries?.find(e=>e.exercise===name);if(e)return e}return null}
function exerciseTotals(){return P.filter(d=>d[2].length).reduce((o,d)=>{d[2].forEach(e=>{let tag=e[3].replace(/ #\d+$/,'');o[tag]=(o[tag]||0)+parseRange(e[1]).sets});return o},{})}
function weeklySets(){let total=0;Object.values(exerciseTotals()).forEach(x=>total+=x);return total}
function workout(){
 const d=P[S.day],entries=S.active?.day===S.day?S.active.entries:{};
 if(!d[2].length){document.getElementById('workout').innerHTML=`<div class="hero rest-hero"><div class="hero-copy"><div class="eyebrow">DAY ${S.day+1} · RECOVERY</div><h2>Recover hard.</h2><p>Keep activity easy, eat well, and let your next session hit fresh.</p></div><div class="hero-orb">REST</div></div><div class="section-label">TODAY</div><div class="card recovery-card"><div class="big-check">✓</div><div><h3>No workout scheduled</h3><p>Light walking, mobility, hydration and sleep. You don't need to force a session.</p></div></div><button class="ghost wide" data-program>View program</button>`;document.querySelector('[data-program]')?.addEventListener('click',()=>view('program'));return}
 const total=d[2].reduce((a,e)=>a+parseRange(e[1]).sets,0),done=Object.values(entries).reduce((a,e)=>a+(e?.done?1:0),0),pct=Math.min(100,Math.round(done/total*100));
 const loggedSets=Object.values(entries).filter(x=>x?.done).length;
 let h=`<div class="workout-hero"><div class="hero-top"><div><div class="eyebrow">DAY ${S.day+1} · TODAY</div><h2>${esc(d[0].replace(/^DAY \d+ — /,''))}</h2><p>${esc(d[1])}</p></div><div class="hero-count"><strong>${done}</strong><span>/ ${total}</span><small>SETS</small></div></div><div class="hero-progress"><span style="width:${pct}%"></span></div><div class="hero-meta"><span>${pct}% complete</span><span>${d[2].length} exercises</span></div></div>`;
 if(S.timer?.end)h+=timerHtml();
 d[2].forEach((e,i)=>{let r=parseRange(e[1]),prev=lastForExercise(e[0]),active=i===nextExerciseIndex(entries,d[2]);h+=`<article class="exercise-card ${active?'is-next':''}"><div class="exercise-visual"><div class="visual-number">${String(i+1).padStart(2,'0')}</div><div class="visual-lines"><i></i><i></i><i></i></div><span>${esc(e[3])}</span></div><div class="exercise-content"><div class="exercise-heading"><div><h3>${esc(e[0])}</h3><p>${esc(e[1])} <b>·</b> RIR ${esc(e[2])}</p></div>${active?'<span class="next-badge">NEXT</span>':''}</div>${prev?`<div class="last-box"><div><small>LAST SESSION</small><strong>${esc(prev.summary||'Logged')}</strong></div><span>↗</span></div>`:`<div class="last-box muted-box"><div><small>FIRST LOG</small><strong>Set your baseline today</strong></div></div>`}<div class="set-header"><span>SET</span><span>KG</span><span>REPS</span><span></span></div>`;
 for(let s=1;s<=r.sets;s++){let key=`${i}-${s}`,v=entries[key]||{},checked=v.done?'checked':'';h+=`<div class="set-row ${checked}"><span class="set-index">${s}</span><input class="input set-input" data-e="${i}" data-s="${s}" data-t="w" inputmode="decimal" placeholder="—" value="${esc(v.w||'')}"><input class="input set-input" data-e="${i}" data-s="${s}" data-t="r" inputmode="numeric" placeholder="${r.min}–${r.max}" value="${esc(v.r||'')}"><button class="done ${checked}" data-e="${i}" data-s="${s}" aria-label="Complete set">✓</button></div>`}
 h+=`</div></article>`});
 h+=`<button class="finish-btn" id="finish"><span>${loggedSets===total?'✓':'→'}</span>${loggedSets===total?'Finish workout':'Finish & save workout'}</button><p class="session-note">Your data stays on this device. Previous performance will appear automatically next time.</p>`;
 document.getElementById('workout').innerHTML=h;
 bindWorkout(d);
}
function nextExerciseIndex(entries,ex){for(let i=0;i<ex.length;i++){let r=parseRange(ex[i][1]);for(let s=1;s<=r.sets;s++)if(!entries[`${i}-${s}`]?.done)return i}return -1}
function bindWorkout(d){
 document.querySelectorAll('.set-input').forEach(inp=>inp.addEventListener('input',()=>{let key=`${inp.dataset.e}-${inp.dataset.s}`;S.active=S.active||{day:S.day,entries:{}};S.active.entries=S.active.entries||{};S.active.entries[key]=S.active.entries[key]||{};S.active.entries[key][inp.dataset.t]=inp.value;save()}));
 document.querySelectorAll('.done').forEach(b=>b.onclick=()=>{let key=`${b.dataset.e}-${b.dataset.s}`;S.active=S.active||{day:S.day,entries:{}};S.active.entries=S.active.entries||{};S.active.entries[key]=S.active.entries[key]||{};let val=S.active.entries[key].done=!S.active.entries[key].done;save();workout();if(val)startTimer(120)});
 document.getElementById('finish')?.addEventListener('click',finishWorkout);
 document.querySelectorAll('[data-timer]').forEach(b=>b.onclick=()=>{let a=b.dataset.timer;if(a==='plus'){S.timer.end+=30000;save();workout()}else if(a==='skip'){S.timer=null;save();workout()}else if(a==='pause'){if(S.timer.paused){let pausedFor=Date.now()-S.timer.pausedAt;S.timer.end+=pausedFor;S.timer.paused=false;S.timer.pausedAt=null}else{S.timer.paused=true;S.timer.pausedAt=Date.now()}save();workout()}});
}
function timerHtml(){let left=S.timer.paused?(S.timer.pausedAt-S.timer.started):Math.max(0,S.timer.end-Date.now());let sec=Math.ceil(left/1000);if(sec<=0){S.timer=null;save();return ''}let m=Math.floor(sec/60),s=String(sec%60).padStart(2,'0');return `<div class="timer"><div class="timer-ring"><strong>${m}:${s}</strong><small>REST</small></div><div><b>Recover</b><span>Next set when you're ready.</span></div><div class="timer-actions"><button data-timer="plus">+30</button><button data-timer="pause">${S.timer.paused?'Resume':'Pause'}</button><button data-timer="skip">Skip</button></div></div>`}
function startTimer(seconds){S.timer={started:Date.now(),end:Date.now()+seconds*1000,paused:false};save();workout();clearInterval(window.__timer);window.__timer=setInterval(()=>{if(!S.timer)return;if(S.timer.paused)return;if(Date.now()>=S.timer.end){S.timer=null;save();clearInterval(window.__timer);toast('Rest complete — next set');workout();return}let el=document.querySelector('.timer-ring strong');if(el){let sec=Math.ceil((S.timer.end-Date.now())/1000);el.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}},500)}
function finishWorkout(){let d=P[S.day],entries=S.active?.entries||{},rows=[];d[2].forEach((e,i)=>{let r=parseRange(e[1]),sets=[];for(let s=1;s<=r.sets;s++){let v=entries[`${i}-${s}`]||{};if(v.w||v.r)sets.push({w:v.w||'',r:v.r||''})}if(sets.length)rows.push({exercise:e[0],sets,summary:sets.map(x=>`${x.w||'—'}×${x.r||'—'}`).join(', ')})});if(!rows.length)return toast('Log at least one set first');S.workouts.push({date:today(),day:d[0],entries:rows});S.active=null;S.timer=null;save();showComplete(d,rows)}
function showComplete(d,rows){let sets=rows.reduce((a,e)=>a+e.sets.length,0),reps=rows.reduce((a,e)=>a+e.sets.reduce((b,s)=>b+(+s.r||0),0),0);document.getElementById('workout').innerHTML=`<div class="completion"><div class="completion-mark">✓</div><div class="eyebrow">SESSION COMPLETE</div><h2>That's the work.</h2><p>${esc(d[0].replace(/^DAY \d+ — /,''))} is saved. Your next session will use it as the benchmark.</p><div class="completion-stats"><div><strong>${sets}</strong><span>sets</span></div><div><strong>${reps||'—'}</strong><span>reps</span></div><div><strong>${rows.length}</strong><span>exercises</span></div></div></div><button class="finish-btn" id="backHome">Back to today</button><button class="ghost wide" data-progress>See progress</button>`;document.getElementById('backHome').onclick=()=>workout();document.querySelector('[data-progress]').onclick=()=>view('progress');toast('Workout saved ✓')}
function program(){let activeDay=S.day;let h=`<div class="page-head"><div class="eyebrow">YOUR PROGRAM</div><h2>Train with intent.</h2><p>5 lifting days · upper chest, shoulders, arms, calves and upper back prioritized.</p></div><div class="week-strip">${P.map((d,i)=>`<button class="day-chip ${i===activeDay?'active':''}" data-day="${i}"><b>${i+1}</b><span>${d[0].includes('REST')?'REST':d[0].split('—')[1].trim().split(' ')[0]}</span></button>`).join('')}</div>`;
 P.forEach((d,i)=>{if(i!==activeDay)return;let rest=!d[2].length;h+=`<div class="program-feature"><div class="program-feature-top"><div><div class="eyebrow">DAY ${i+1}</div><h3>${esc(d[0].replace(/^DAY \d+ — /,''))}</h3><p>${esc(d[1])}</p></div>${rest?'<span class="pill">REST</span>':`<button class="start-btn" data-start="${i}">Start →</button>`}</div>`;if(!rest)d[2].forEach((e,j)=>h+=`<div class="program-exercise"><div class="program-num">${String(j+1).padStart(2,'0')}</div><div><strong>${esc(e[0])}</strong><small>${esc(e[3])}</small></div><span>${esc(e[1])}</span></div>`);h+='</div>'});
 h+=`<div class="section-label">WEEKLY VOLUME</div><div class="volume-card">${Object.entries(exerciseTotals()).map(([k,v])=>`<div class="volume-row"><div><span>${esc(k)}</span><b>${v}</b></div><div class="mini-bar"><i style="width:${Math.min(100,v/18*100)}%"></i></div></div>`).join('')}</div>`;
 document.getElementById('program').innerHTML=h;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{S.day=+b.dataset.day;save();program()});document.querySelectorAll('[data-start]').forEach(b=>{b.onclick=()=>{S.day=+b.dataset.start;S.active=null;save();view('workout')}})}
function sparkline(values){if(values.length<2)return '<div class="chart-empty">Add at least two check-ins to see your trend.</div>';let min=Math.min(...values),max=Math.max(...values),range=max-min||1;let pts=values.map((v,i)=>`${(i/(values.length-1))*100},${100-((v-min)/range)*76-12}`).join(' ');return `<svg class="spark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2.8" vector-effect="non-scaling-stroke"/><polyline points="${pts.split(' ').slice(-1)[0]} 100,0 100" fill="currentColor" opacity=".06"/></svg>`}
function progress(){let m=S.metrics,last=m[m.length-1]||{},prev=m[m.length-2]||{},wd=last.weight&&prev.weight?(+last.weight-+prev.weight).toFixed(1):null,workouts=S.workouts.length,weights=m.map(x=>+x.weight).filter(Boolean),setsThisWeek=weeklySets();
 document.getElementById('progress').innerHTML=`<div class="page-head"><div class="eyebrow">PROGRESS</div><h2>Build. Measure. Adjust.</h2><p>Keep the trend moving while your lifts stay strong.</p></div><div class="metric-grid"><div class="metric-card featured"><small>BODYWEIGHT</small><strong>${last.weight||'—'}<em>kg</em></strong><span>${wd?`${wd>0?'+':''}${wd} kg vs previous`:'Add your first check-in'}</span></div><div class="metric-card"><small>WORKOUTS</small><strong>${workouts}</strong><span>logged sessions</span></div><div class="metric-card"><small>WAIST</small><strong>${last.waist||'—'}<em>cm</em></strong><span>latest check-in</span></div></div><div class="section-label">BODYWEIGHT TREND</div><div class="chart-card">${weights.length?sparkline(weights):'<div class="chart-empty">Your bodyweight trend will appear here.</div>'}<div class="chart-labels"><span>${weights[0]||'—'} kg</span><b>${weights[weights.length-1]||'—'} kg</b></div></div><div class="section-label">TRAINING FOCUS</div><div class="focus-card"><div class="focus-head"><span>Weekly programmed sets</span><strong>${setsThisWeek}</strong></div><div class="focus-grid">${Object.entries(exerciseTotals()).map(([k,v])=>`<div><span>${esc(k)}</span><b>${v}</b><i><u style="width:${Math.min(100,v/18*100)}%"></u></i></div>`).join('')}</div></div><div class="section-label">NEW CHECK-IN</div><div class="checkin-card"><div class="grid"><div class="field"><label>Date</label><input id="md" class="input" type="date" value="${today()}"></div><div class="field"><label>Weight kg *</label><input id="mw" class="input" inputmode="decimal"></div><div class="field"><label>Waist cm</label><input id="mz" class="input" inputmode="decimal"></div><div class="field"><label>Avg calories</label><input id="mc" class="input" inputmode="numeric"></div><div class="field"><label>Protein g</label><input id="mp" class="input" inputmode="numeric"></div><div class="field"><label>Steps</label><input id="ms" class="input" inputmode="numeric"></div></div><button class="finish-btn" id="saveM">Save check-in</button></div><div class="section-label">RECENT CHECK-INS</div><div class="list-card">${m.slice().reverse().map(x=>`<div class="history-row"><div><strong>${esc(x.date)}</strong><small>${x.waist?esc(x.waist)+' cm waist · ':''}${x.protein?esc(x.protein)+'g protein':''}</small></div><b>${esc(x.weight)} kg</b></div>`).join('')||'<div class="empty">No check-ins yet.</div>'}</div>`;
 document.getElementById('saveM').onclick=()=>{let w=parseFloat(document.getElementById('mw').value);if(!w)return toast('Enter weight first');S.metrics.push({date:document.getElementById('md').value,weight:w,waist:document.getElementById('mz').value,cal:document.getElementById('mc').value,protein:document.getElementById('mp').value,steps:document.getElementById('ms').value});S.metrics.sort((a,b)=>a.date.localeCompare(b.date));save();toast('Check-in saved ✓');progress()}
}
function history(){let h=`<div class="page-head"><div class="eyebrow">HISTORY</div><h2>Keep the receipts.</h2><p>${S.workouts.length} logged workout${S.workouts.length===1?'':'s'} · local to this device.</p></div>`;if(!S.workouts.length)h+=`<div class="empty-panel"><div>◷</div><h3>No sessions yet</h3><p>Finish your first workout and your training history will build here.</p><button class="start-btn" data-go>Start training →</button></div>`;else{h+='<div class="history-stack">';S.workouts.slice().reverse().forEach((x,idx)=>{let sets=(x.entries||[]).reduce((a,e)=>a+(e.sets?.length||0),0),reps=(x.entries||[]).reduce((a,e)=>a+(e.sets||[]).reduce((b,s)=>b+(+s.r||0),0),0);h+=`<article class="history-card"><div class="history-date"><span>${esc(x.date)}</span><b>${String(S.workouts.length-idx).padStart(2,'0')}</b></div><div><h3>${esc(x.day.replace(/^DAY \d+ — /,''))}</h3><p>${sets} sets · ${reps||'—'} reps · ${x.entries?.length||0} exercises</p></div><span class="history-arrow">›</span></article>`});h+='</div>'}document.getElementById('history').innerHTML=h;document.querySelector('[data-go]')?.addEventListener('click',()=>view('workout'))}
function settings(){document.getElementById('settings').innerHTML=`<div class="page-head"><div class="eyebrow">MORE</div><h2>Make it yours.</h2><p>Local-first. Private. Yours.</p></div><div class="settings-card"><div class="setting-row"><div><strong>Install app</strong><small>Add Gym Tracker to your phone home screen.</small></div><button class="secondary" id="install2">Install</button></div><div class="setting-row"><div><strong>Export backup</strong><small>Save all workouts and check-ins as JSON.</small></div><button class="secondary" id="export">Export</button></div><div class="setting-row danger-row"><div><strong>Reset all data</strong><small>This cannot be undone.</small></div><button class="secondary danger" id="reset">Reset</button></div></div><div class="tip-card"><div class="eyebrow">RETURNING AFTER A BREAK?</div><h3>Ramp back in.</h3><p>Week 1: 50–60% volume, 3–4 RIR.<br>Week 2: 75–80%, 2–3 RIR.<br>Week 3+: full volume, 1–3 RIR.</p></div><div class="version">GYM TRACKER · V3 · LOCAL-FIRST PWA</div>`;document.getElementById('install2').onclick=()=>window.deferred?.prompt()||toast('Use your browser menu to install this app');document.getElementById('export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='gym-tracker-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')};document.getElementById('reset').onclick=()=>{if(confirm('Delete all workout and body data?')){S={day:0,workouts:[],metrics:[],active:null};save();settings();toast('Reset complete')}}}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>view(b.dataset.v));document.getElementById('close').onclick=()=>document.getElementById('modal').classList.add('hidden');render('workout');
if(S.timer?.end){clearInterval(window.__timer);window.__timer=setInterval(()=>{if(!S.timer||S.timer.paused)return;if(Date.now()>=S.timer.end){S.timer=null;save();clearInterval(window.__timer);toast('Rest complete — next set');workout();return}let el=document.querySelector('.timer-ring strong');if(el){let sec=Math.ceil((S.timer.end-Date.now())/1000);el.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}},500)}
const topbar=document.querySelector('.topbar');window.addEventListener('scroll',()=>topbar.classList.toggle('scrolled',window.scrollY>8),{passive:true});document.querySelector('.brand').addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.deferred=e;document.getElementById('install').classList.remove('hidden')});document.getElementById('install').onclick=()=>window.deferred?.prompt();
