/* V4.3 enhancement layer: progression engine, PRs, history detail, import, exercise reference cards. */
(function(){
const esc0=esc;
const originalWorkout=window.workout;
const originalProgram=window.program;
const originalProgress=window.progress;
const originalHistory=window.history;

function exKey(name){return name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function rangeFor(name){const d=P.flatMap(x=>x[2]).find(e=>e[0]===name);return d?parseRange(d[1]):{sets:1,min:1,max:99}}
function lastEntry(name){return lastForExercise(name)}
function setsFromEntry(e){return e?.sets||[]}
function bestWeight(name){let best=0;S.workouts.forEach(w=>(w.entries||[]).forEach(e=>{if(e.exercise===name)setsFromEntry(e).forEach(x=>best=Math.max(best,parseFloat(x.w)||0))}));return best}
function bestRepsAtWeight(name,weight){let best=0;S.workouts.forEach(w=>(w.entries||[]).forEach(e=>{if(e.exercise===name)setsFromEntry(e).forEach(x=>{if(Math.abs((parseFloat(x.w)||0)-weight)<.001)best=Math.max(best,parseInt(x.r)||0)})}));return best}
function suggestion(name){const r=rangeFor(name),last=lastEntry(name),sets=setsFromEntry(last),target=[];
 if(!last||!sets.length)return {label:'SET A BASELINE',detail:`Aim for ${r.min}–${r.max} reps with ${last?.rir||'your planned'} RIR.`,weight:'',reps:r.min};
 sets.forEach((x,i)=>{let w=parseFloat(x.w)||0,rep=parseInt(x.r)||0;if(!w||!rep){target.push({w:x.w||'',r:r.min});return}if(rep<r.max)target.push({w,r:Math.min(r.max,rep+1)});else target.push({w:w*1.025,r:r.min})});
 const totalLast=sets.reduce((a,x)=>a+(parseInt(x.r)||0),0), maxTotal=r.max*r.sets, label=totalLast>=maxTotal?`INCREASE LOAD`:`BEAT ${totalLast} REPS`;
 return {label,detail:totalLast>=maxTotal?`You reached the top of the rep range. Try a small load increase.`:`Add 1 rep to one or more sets before adding weight.`,targets:target,totalLast};}
function calc1RM(w,r){w=parseFloat(w)||0;r=parseFloat(r)||0;return w*(1+r/30)}
function exercisePR(name, current){let prs=[];const bw=[];S.workouts.forEach(w=>(w.entries||[]).forEach(e=>{if(e.exercise===name)setsFromEntry(e).forEach(x=>bw.push({w:parseFloat(x.w)||0,r:parseInt(x.r)||0,date:w.date}))}));const maxW=Math.max(0,...bw.map(x=>x.w)),max1=Math.max(0,...bw.map(x=>calc1RM(x.w,x.r)));current.forEach(x=>{const ww=parseFloat(x.w)||0,rr=parseInt(x.r)||0;if(ww>maxW&&ww)prs.push('LOAD PR');if(calc1RM(ww,rr)>max1&&ww&&rr)prs.push('STRENGTH PR');});return [...new Set(prs)]}
function allExercises(){return P.flatMap(d=>d[2]).map(e=>e[0]).filter((x,i,a)=>a.indexOf(x)===i)}
function visual(name){const n=exKey(name);return `<div class="exercise-art art-${n}"><div class="art-floor"></div><div class="art-person"><i></i><b></b><em></em></div><span>${esc0(name)}</span></div>`}
function detail(name){const last=lastEntry(name), r=rangeFor(name), all=[];S.workouts.forEach(w=>(w.entries||[]).forEach(e=>{if(e.exercise===name)all.push({date:w.date,sets:e.sets||[]})}));let max=0,vol=0;all.forEach(x=>(x.sets||[]).forEach(s=>{const w=parseFloat(s.w)||0,rep=parseInt(s.r)||0;max=Math.max(max,w);vol+=w*rep}));const s=suggestion(name);document.getElementById('modalbody').innerHTML=`<div class="detail-hero">${visual(name)}<div class="detail-title"><div class="eyebrow">EXERCISE</div><h2>${esc0(name)}</h2><p>${r.sets} sets · ${r.min}–${r.max} reps</p></div></div><div class="detail-grid"><div><small>BEST LOAD</small><strong>${max||'—'}<i>kg</i></strong></div><div><small>EST. 1RM</small><strong>${last?.sets?.length?Math.round(Math.max(...last.sets.map(x=>calc1RM(x.w,x.r)))):'—'}<i>kg</i></strong></div><div><small>SESSIONS</small><strong>${all.length}</strong></div></div><div class="smart-box"><span>SMART PROGRESSION</span><strong>${esc0(s.label)}</strong><p>${esc0(s.detail)}</p></div><div class="detail-section"><div class="section-label">RECENT PERFORMANCE</div>${all.slice(-8).reverse().map(x=>`<div class="detail-row"><span>${esc0(x.date)}</span><b>${x.sets.map(y=>`${esc0(y.w||'—')} × ${esc0(y.r||'—')}`).join(' · ')}</b></div>`).join('')||'<div class="empty">No history yet.</div>'}</div>`;document.getElementById('modal').classList.remove('hidden')}
function renderEnhancedWorkout(){
 const d=P[S.day],entries=S.active?.day===S.day?S.active.entries:{};
 if(!d[2].length){originalWorkout();return}
 const total=d[2].reduce((a,e)=>a+parseRange(e[1]).sets,0),done=Object.values(entries).filter(x=>x?.done).length,pct=Math.round(done/total*100),next=nextExerciseIndex(entries,d[2]);
 let h=`<div class="today-intro"><div><div class="eyebrow">MONDAY · DAY ${S.day+1}</div><h2>${esc0(d[0].replace(/^DAY \d+ — /,''))}</h2><p>${esc0(d[1])}</p></div><div class="session-score"><strong>${done}</strong><span>/${total}</span><small>SETS</small></div></div><div class="progress-track"><i style="width:${pct}%"></i></div>`;
 if(S.timer?.end) h+=timerHtml();
 if(next>=0) h+=`<div class="up-next"><span>NEXT UP</span><strong>${esc0(d[2][next][0])}</strong><small>Keep the target in mind. One set at a time.</small></div>`;
 d[2].forEach((e,i)=>{const r=parseRange(e[1]),prev=lastEntry(e[0]),s=suggestion(e[0]),isNext=i===next;h+=`<article class="neo-exercise ${isNext?'is-next':''}"><button class="exercise-cover" data-detail="${esc0(e[0])}">${visual(e[0])}<span class="exercise-tag">${esc0(e[3])}</span><span class="open-detail">↗</span></button><div class="neo-body"><div class="neo-title"><div><span class="exercise-num">${String(i+1).padStart(2,'0')}</span><h3>${esc0(e[0])}</h3><p>${esc0(e[1])} · RIR ${esc0(e[2])}</p></div>${isNext?'<b class="next-pill">NEXT</b>':''}</div><div class="smart-target"><span>${esc0(s.label)}</span><strong>${esc0(s.detail)}</strong></div><div class="last-line"><span>LAST</span><b>${prev?esc0(prev.summary||prev.sets?.map(x=>`${x.w}×${x.r}`).join(' · ')):'Baseline today'}</b></div>`;
 for(let set=1;set<=r.sets;set++){let key=`${i}-${set}`,v=entries[key]||{},checked=v.done?'is-done':'';let sug=s.targets?.[set-1]||{w:'',r:r.min};h+=`<div class="neo-set ${checked}"><span>${String(set).padStart(2,'0')}</span><input class="input set-input" data-e="${i}" data-s="${set}" data-t="w" inputmode="decimal" placeholder="${sug.w||'KG'}" value="${esc0(v.w||'')}"><b>×</b><input class="input set-input" data-e="${i}" data-s="${set}" data-t="r" inputmode="numeric" placeholder="${sug.r||r.min}" value="${esc0(v.r||'')}"><button class="done ${checked}" data-e="${i}" data-s="${set}">${checked?'✓':'○'}</button></div>`}
 h+=`<textarea class="exercise-note" data-note="${i}" placeholder="Add a note for this exercise…">${esc0(entries[`note-${i}`]?.note||'')}</textarea></div></article>`});
 h+=`<button class="finish-btn neo-finish" id="finish"><span>${done===total?'✓':'→'}</span>${done===total?'Finish session':'Save & finish'}</button><div class="microcopy">Targets adapt from your previous performance. Your log stays on this device.</div>`;
 document.getElementById('workout').innerHTML=h;bindEnhancedWorkout(d);
}
function bindEnhancedWorkout(d){document.querySelectorAll('.set-input').forEach(inp=>inp.addEventListener('input',()=>{let key=`${inp.dataset.e}-${inp.dataset.s}`;S.active=S.active||{day:S.day,entries:{}};S.active.entries=S.active.entries||{};S.active.entries[key]=S.active.entries[key]||{};S.active.entries[key][inp.dataset.t]=inp.value;save()}));
 document.querySelectorAll('.exercise-note').forEach(t=>t.addEventListener('input',()=>{let k=`note-${t.dataset.note}`;S.active=S.active||{day:S.day,entries:{}};S.active.entries[k]=S.active.entries[k]||{};S.active.entries[k].note=t.value;save()}));
 document.querySelectorAll('.done').forEach(b=>b.onclick=()=>{let key=`${b.dataset.e}-${b.dataset.s}`;S.active=S.active||{day:S.day,entries:{}};S.active.entries=S.active.entries||{};S.active.entries[key]=S.active.entries[key]||{};let val=S.active.entries[key].done=!S.active.entries[key].done;save();renderEnhancedWorkout();if(val)startTimer(120)});
 document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));document.getElementById('finish')?.addEventListener('click',finishEnhanced);document.querySelectorAll('[data-timer]').forEach(b=>b.onclick=()=>{let a=b.dataset.timer;if(a==='plus'){S.timer.end+=30000;save();renderEnhancedWorkout()}else if(a==='skip'){S.timer=null;save();renderEnhancedWorkout()}else if(a==='pause'){if(S.timer.paused){S.timer.end+=Date.now()-S.timer.pausedAt;S.timer.paused=false;S.timer.pausedAt=null}else{S.timer.paused=true;S.timer.pausedAt=Date.now()}save();renderEnhancedWorkout()}})}
function finishEnhanced(){let d=P[S.day],entries=S.active?.entries||{},rows=[],prs=[];d[2].forEach((e,i)=>{let r=parseRange(e[1]),sets=[];for(let s=1;s<=r.sets;s++){let v=entries[`${i}-${s}`]||{};if(v.w||v.r)sets.push({w:v.w||'',r:v.r||''})}if(sets.length){rows.push({exercise:e[0],sets,summary:sets.map(x=>`${x.w||'—'}×${x.r||'—'}`).join(', '),note:entries[`note-${i}`]?.note||''});prs.push(...exercisePR(e[0],sets))}});if(!rows.length)return toast('Log at least one set first');const totalVol=rows.reduce((a,e)=>a+e.sets.reduce((b,s)=>b+(parseFloat(s.w)||0)*(parseFloat(s.r)||0),0),0);S.workouts.push({date:today(),day:d[0],entries:rows,volume:Math.round(totalVol),prs:[...new Set(prs)]});S.active=null;S.timer=null;save();showEnhancedComplete(d,rows,totalVol,[...new Set(prs)])}
function showEnhancedComplete(d,rows,vol,prs){const sets=rows.reduce((a,e)=>a+e.sets.length,0),reps=rows.reduce((a,e)=>a+e.sets.reduce((b,s)=>b+(+s.r||0),0),0);document.getElementById('workout').innerHTML=`<div class="completion-neo"><div class="completion-glow">✓</div><div class="eyebrow">SESSION SAVED</div><h2>That's the work.</h2><p>${esc0(d[0].replace(/^DAY \d+ — /,''))} is in the books.</p><div class="completion-grid"><div><strong>${sets}</strong><span>sets</span></div><div><strong>${reps}</strong><span>reps</span></div><div><strong>${Math.round(vol).toLocaleString()}</strong><span>kg volume</span></div></div>${prs.length?`<div class="pr-banner"><span>🏆</span><div><b>${prs.length} PR${prs.length>1?'s':''}</b><small>${esc0(prs.join(' · '))}</small></div></div>`:''}<button class="finish-btn" id="backHome">Back to today</button><button class="ghost wide" id="seeProgress">See progress</button></div>`;document.getElementById('backHome').onclick=()=>renderEnhancedWorkout();document.getElementById('seeProgress').onclick=()=>view('progress');toast(prs.length?`Workout saved · ${prs.length} PR${prs.length>1?'s':''} 🏆`:'Workout saved ✓')}
function enhancedProgram(){let active=S.day,h=`<div class="page-head neo-head"><div class="eyebrow">YOUR TRAINING SYSTEM</div><h2>Train with intent.</h2><p>Built around your hypertrophy priorities, with progression baked in.</p></div><div class="day-rail">${P.map((d,i)=>`<button class="day-chip ${i===active?'active':''}" data-day="${i}"><b>${i+1}</b><span>${d[0].includes('REST')?'REST':d[0].split('—')[1].trim().split(' ')[0]}</span></button>`).join('')}</div>`;const d=P[active];h+=`<div class="program-hero"><div><span class="eyebrow">DAY ${active+1}</span><h3>${esc0(d[0].replace(/^DAY \d+ — /,''))}</h3><p>${esc0(d[1])}</p></div>${d[2].length?`<button class="start-btn" data-start="${active}">Start →</button>`:'<span class="pill">RECOVER</span>'}</div>`;d[2].forEach((e,i)=>{const last=lastEntry(e[0]);h+=`<button class="program-tile" data-detail="${esc0(e[0])}"><span class="tile-number">${String(i+1).padStart(2,'0')}</span>${visual(e[0])}<div><strong>${esc0(e[0])}</strong><small>${esc0(e[1])} · RIR ${esc0(e[2])}</small>${last?`<em>Last · ${esc0(last.summary||'logged')}</em>`:'<em>Ready for baseline</em>'}</div><b>›</b></button>`});h+=`<div class="section-label">PROGRAMMED WEEKLY VOLUME</div><div class="volume-card neo-volume">${Object.entries(exerciseTotals()).map(([k,v])=>`<div class="volume-row"><div><span>${esc0(k)}</span><b>${v}</b></div><div class="mini-bar"><i style="width:${Math.min(100,v/18*100)}%"></i></div></div>`).join('')}</div>`;document.getElementById('program').innerHTML=h;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{S.day=+b.dataset.day;save();enhancedProgram()});document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{const target=+b.dataset.start;if(S.active&&S.active.day!==target&&Object.keys(S.active.entries||{}).length&&!confirm('You have an unfinished workout in progress. Switch days and discard it?'))return;S.day=target;S.active=null;save();view('workout')});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail))}
function enhancedProgress(){const m=S.metrics,last=m[m.length-1]||{},prev=m[m.length-2]||{},weights=m.map(x=>+x.weight).filter(Boolean),wd=last.weight&&prev.weight?(+last.weight-+prev.weight).toFixed(1):null;const recent=S.workouts.slice(-4),volume=recent.reduce((a,w)=>a+(w.volume||0),0),prs=S.workouts.reduce((a,w)=>a+(w.prs?.length||0),0);document.getElementById('progress').innerHTML=`<div class="page-head neo-head"><div class="eyebrow">PROGRESS</div><h2>Build. Measure. Adjust.</h2><p>Your body trend and training performance, in one place.</p></div><div class="stat-deck"><div class="big-stat"><span>BODYWEIGHT</span><strong>${last.weight||'—'}<i>kg</i></strong><small>${wd?`${wd>0?'+':''}${wd} kg vs previous`:'Add a check-in'}</small></div><div class="small-stat"><span>SESSIONS</span><strong>${S.workouts.length}</strong></div><div class="small-stat"><span>PRs</span><strong>${prs}</strong></div><div class="small-stat"><span>RECENT VOL.</span><strong>${volume?Math.round(volume/1000*10)/10+'k':'—'}</strong><small>kg</small></div></div><div class="section-label">BODYWEIGHT</div><div class="chart-card neo-chart">${weights.length?sparkline(weights):'<div class="chart-empty">Add two check-ins to unlock your trend.</div>'}<div class="chart-labels"><span>${weights[0]||'—'} kg</span><b>${weights[weights.length-1]||'—'} kg</b></div></div><div class="section-label">MUSCLE FOCUS</div><div class="focus-card neo-focus">${Object.entries(exerciseTotals()).map(([k,v])=>`<div><div><span>${esc0(k)}</span><b>${v} sets</b></div><i><u style="width:${Math.min(100,v/18*100)}%"></u></i></div>`).join('')}</div><div class="section-label">NEW CHECK-IN</div><div class="checkin-card neo-checkin"><div class="grid"><div class="field"><label>Date</label><input id="md" class="input" type="date" value="${today()}"></div><div class="field"><label>Weight kg *</label><input id="mw" class="input" inputmode="decimal"></div><div class="field"><label>Waist cm</label><input id="mz" class="input" inputmode="decimal"></div><div class="field"><label>Avg calories</label><input id="mc" class="input" inputmode="numeric"></div><div class="field"><label>Protein g</label><input id="mp" class="input" inputmode="numeric"></div><div class="field"><label>Steps</label><input id="ms" class="input" inputmode="numeric"></div></div><button class="finish-btn" id="saveM">Save check-in</button></div>`;document.getElementById('saveM').onclick=()=>{let w=parseFloat(document.getElementById('mw').value);if(!w)return toast('Enter weight first');S.metrics.push({date:document.getElementById('md').value,weight:w,waist:document.getElementById('mz').value,cal:document.getElementById('mc').value,protein:document.getElementById('mp').value,steps:document.getElementById('ms').value});S.metrics.sort((a,b)=>a.date.localeCompare(b.date));save();toast('Check-in saved ✓');enhancedProgress()}}
function enhancedHistory(){let h=`<div class="page-head neo-head"><div class="eyebrow">HISTORY</div><h2>Your training receipts.</h2><p>${S.workouts.length} session${S.workouts.length===1?'':'s'} · private on this device.</p></div>`;if(!S.workouts.length)h+=`<div class="empty-panel"><div>◷</div><h3>No sessions yet</h3><p>Finish a workout and the app will start learning your performance.</p><button class="start-btn" data-go>Start training →</button></div>`;else{h+='<div class="history-stack neo-history">';S.workouts.slice().reverse().forEach((x,idx)=>{let sets=(x.entries||[]).reduce((a,e)=>a+(e.sets?.length||0),0),reps=(x.entries||[]).reduce((a,e)=>a+(e.sets||[]).reduce((b,s)=>b+(+s.r||0),0),0);h+=`<button class="history-card" data-history="${S.workouts.length-1-idx}"><div class="history-date"><span>${esc0(x.date)}</span><b>${String(S.workouts.length-idx).padStart(2,'0')}</b></div><div><h3>${esc0(x.day.replace(/^DAY \d+ — /,''))}</h3><p>${sets} sets · ${reps||'—'} reps · ${x.volume?x.volume.toLocaleString()+' kg volume':'—'}</p>${x.prs?.length?`<em>🏆 ${x.prs.length} PR${x.prs.length>1?'s':''}</em>`:''}</div><span class="history-arrow">›</span></button>`});h+='</div>'}document.getElementById('history').innerHTML=h;document.querySelector('[data-go]')?.addEventListener('click',()=>view('workout'));document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{const w=S.workouts[+b.dataset.history];document.getElementById('modalbody').innerHTML=`<div class="eyebrow">${esc0(w.date)}</div><h2>${esc0(w.day.replace(/^DAY \d+ — /,''))}</h2><p class="modal-sub">${w.volume?Math.round(w.volume).toLocaleString()+' kg total volume · ':''}${w.prs?.length?w.prs.length+' PRs':''}</p>${(w.entries||[]).map(e=>`<div class="modal-ex"><strong>${esc0(e.exercise)}</strong><span>${esc0(e.summary||'')}</span>${e.note?`<small>${esc0(e.note)}</small>`:''}</div>`).join('')}`;document.getElementById('modal').classList.remove('hidden')})}
function isStandaloneApp(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function isIOSDevice(){return /iphone|ipad|ipod/i.test(navigator.userAgent)&&!window.MSStream}
function installRowHtml(){
 if(isStandaloneApp())return `<div class="setting-row"><div><strong>Install app</strong><small>Already installed on this device.</small></div><span class="pill">INSTALLED</span></div>`;
 if(isIOSDevice())return `<div class="setting-row"><div><strong>Install app</strong><small>Tap the Share icon in Safari, then "Add to Home Screen".</small></div><span class="pill">⤴ SHARE</span></div>`;
 return `<div class="setting-row"><div><strong>Install app</strong><small>Add Gym Tracker to your home screen.</small></div><button class="secondary" id="install2">Install</button></div>`;
}
function enhancedSettings(){document.getElementById('settings').innerHTML=`<div class="page-head neo-head"><div class="eyebrow">MORE</div><h2>Make it yours.</h2><p>Local-first. Private. No account required.</p></div><div class="settings-card neo-settings">${installRowHtml()}<div class="setting-row"><div><strong>Export backup</strong><small>Download every workout and check-in.</small></div><button class="secondary" id="export">Export</button></div><div class="setting-row"><div><strong>Import backup</strong><small>Restore a JSON backup on this device.</small></div><button class="secondary" id="importBtn">Import</button><input id="importFile" type="file" accept="application/json" hidden></div><div class="setting-row danger-row"><div><strong>Reset all data</strong><small>This cannot be undone.</small></div><button class="secondary danger" id="reset">Reset</button></div></div><div class="tip-card"><div class="eyebrow">PROGRESSION ENGINE</div><h3>Train, don't guess.</h3><p>The app compares your previous performance with today's target, detects PRs, estimates strength and carries your numbers forward automatically.</p></div><div class="version">GYM TRACKER · V5 · LOCAL-FIRST PWA</div>`;document.getElementById('install2')?.addEventListener('click',()=>window.deferred?.prompt()||toast('Use your browser menu to install'));document.getElementById('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='gym-tracker-v43-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};document.getElementById('importBtn').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.workouts||!data.metrics)throw 0;S=data;S.day=S.day??0;S.active=null;save();toast('Backup restored ✓');enhancedSettings()}catch(_){toast('Invalid backup file')}};r.readAsText(f)};document.getElementById('reset').onclick=()=>{if(confirm('Delete all workout and body data?')){S={day:0,workouts:[],metrics:[],active:null};save();enhancedSettings();toast('Reset complete')}}}
window.workout=renderEnhancedWorkout;window.program=enhancedProgram;window.progress=enhancedProgress;window.history=enhancedHistory;window.settings=enhancedSettings;
setTimeout(()=>{document.getElementById('close')?.addEventListener('click',()=>document.getElementById('modal').classList.add('hidden'));window.render('workout')},0);
})();
